# Generated by Django 5.0.2 on 2024-03-13 00:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_quoteforms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteForms',
            new_name='QuoteForm',
        ),
    ]
