# Generated by Django 5.0.2 on 2024-03-13 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_quoteforms_quoteform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteform',
            name='gallons_requested',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
