# Generated by Django 5.0.2 on 2024-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='state', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='zip_code', max_length=10),
        ),
    ]
